name: Gradle project
on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-jar-artifact
          path: build/libs/unit-1.0-SNAPSHOT.jar
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/test-results
