name: Gradle project
on:
  push:
   branches:
      - Assignment
  pull_request:
    branches:
      - Assignment
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Make Gradlew Executable
        run: chmod +x gradlew
        
      - name: Build Gradle project
        run: ./gradlew build


        
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-jar-artifact
          path: build/libs/unit-1.0-SNAPSHOT.jar
      - name: Upload Test Report New
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/test-results
# setup gradle
#setup java
#gradle build
